services:
  - type: web
    name: greenwood-strapi
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: greenwood-db
          property: connectionString
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true

databases:
  - name: greenwood-db
    plan: free
    databaseName: greenwood
    user: greenwood



